# cluster specific values
cluster:
  # specify cluster name
  name: single-node-k3s-125

  # specify cluster labels
  labels: 
    demo-app: install

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""

